id: PFFCA60F8
initial_creation_type: input
source_metadata:
  title: Katok Dampa Deshek Series
  language: fr
  description: 'Texts by Katok Dampa Deshek (kaḥ thog dam pa bde gshegs, 1122–1192),
    the founder of Katok Monastery:'
  volume:
    5904a7e9ed484aacba703c24088ff923:
      title: The Last Testament of Katok Dampa Deshek
      parent: Last Testament
created_at: '2022-03-01T00:13:09.690546'
last_modified_at: '2022-03-01T00:13:09.690548'
